### PR TITLE
Update PHP CI images

### PR DESCRIPTION
**Pull request by nupplaphil**
This CI images will be used for moving the PHP core tests from github actions to drone :-)

### CODE REVIEW

**Comment by nupplaphil** [comment]
PHP image are used here: https://github.com/friendica/friendica/pull/10251

**Comment by nupplaphil** [comment]
Ping @MrPetovan for approval :)

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
I'm going to pretend I know what I'm doing here.

**Comment by nupplaphil** [comment]
@MrPetovan - these are the prepared docker images for the Drone - pipeline, so we don't need to install every dependency at every run. And they're also including some scripts we do need during the workflow (like the `check-messages.sh` for the transifex check)

**Pull request merged**
